version: "3"
services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: dev
    volumes:
      - ../src:/app/src
      - ../node_modules:/app/node_modules
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
